### ISSUE TITLE
hardhat-abi-exporter: duplicate output destination:

### ISSUE THREAD

**Issue by defido** [ItsNickBarry/hardhat-abi-exporter#39]
I am trying to deploy a contract, and each version has the same error message, deleting the ABI folder does nothing, deleting all cache folders and other compile time folders also doesn't work. 

`Error in plugin hardhat-abi-exporter: duplicate output destination: /Users/computer/folder/testCoin-4/abis/Ownable.json`

I have tried running clear & also trying a fresh install.  I have also changed folder names, and moved their destination, starting from a fresh starter also doesn't help.

` abiExporter: {
    path: "./abis",
    runOnCompile: true,
    clear: true,
    flat: true,
    only: [],
    spacing: 2,
    pretty: true,
  },`

**Comment by ItsNickBarry** [comment]
The `flat` option will cause two contracts with different paths but the same name to have the same ABI output path. For example, both `contracts/File.sol` and `contracts/folder/File.sol` will have their ABIs exported to `abi/File.json`.

Remove the `flat` option, or use `only` and `except` to be ore specific about which files you want to generate ABIs for.

**Comment by defido** [comment]
Ok, thanks, that opened up another error, I'll try work it out.

`reason: 'invalid address (argument="address", value=undefined, code=INVALID_ARGUMENT, version=address/5.6.0)',`

`Error: invalid address (argument="address", value=undefined, code=INVALID_ARGUMENT, version=address/5.6.0) (argument="_add1", value=undefined, code=INVALID_ARGUMENT, version=abi/5.6.0)`
