### ISSUE TITLE
[suggestion] add bin-exporter

### ISSUE THREAD

**Issue by dawnkie** [ItsNickBarry/hardhat-abi-exporter#44]
Hello, author! I have a suggestion: Maybe, the plugin could be added a function: export .bin file, Why?

**Becouse .abi + .bin could generate .go/.java/.objc abi-object-file by abigen(thus [hardhat-abi-exporter](https://github.com/ItsNickBarry/hardhat-abi-exporter) plugin will be more useful, not only for ethers or web3js), eg:** 

[^ plus]: .bin file content is bytecode without `0x` in raw Oracle.json, like this:
```json
{
  // ...
  "bytecode": "0x60806040523480156200001157600080fd5b5060405162001ac638038062001...",
  "deployedBytecode": "0x608060405234801561001057600080fd5b50600436106100a9576000...",
  "linkReferences": {},
  "deployedLinkReferences": {}
}
```

                                              ↓↓↓↓

```txt
60806040523480156200001157600080fd5b50604051620031d3380380620031d383398181016040528101...
```
 ( :: output File name suffix is not important, it's up to you, but maybe `.bin` for bytecode and `.abi` for abi are more accurate)
 '
 
 '

 '
abigen target file like this: 
```shell
abigen --bin Oracle.bin --abi Oracle.abi --pkg oracle -o oracle.go
```
```go
// Code generated - DO NOT EDIT.
// This file is a generated binding and any manual changes will be lost.

package oracle

import (
	"errors"
	"math/big"
	"strings"

	ethereum "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = errors.New
	_ = big.NewInt
	_ = strings.NewReader
	_ = ethereum.NotFound
	_ = bind.Bind
	_ = common.Big1
	_ = types.BloomLookup
	_ = event.NewSubscription
)

// OracleMetaData contains all meta data concerning the Oracle contract.
var OracleMetaData = &bind.MetaData{
	ABI: "[{\"inputs\":[],\"name\":\"ETH\",\"outputs\":...",
}

// OracleABI is the input ABI used to generate the binding from.
// Deprecated: Use OracleMetaData.ABI instead.
var OracleABI = OracleMetaData.ABI

// Oracle is an auto generated Go binding around an Ethereum contract.
type Oracle struct {
	OracleCaller     // Read-only binding to the contract
	OracleTransactor // Write-only binding to the contract
	OracleFilterer   // Log filterer for contract events
}
// has more...
```

salute!

**Comment by ItsNickBarry** [comment]
Similar to #13.  I believe that this feature is out of scope of this plugin, especially as more ABI-specific configuration options are added.  I've had enough requests for this that I think it makes sense to release a separate bytecode exporter plugin.  I do not know when I will have time to do this, however.

**Comment by ItsNickBarry** [comment]
Bytecode exporter plugin released: https://github.com/solidstate-network/hardhat-bytecode-exporter
