### ISSUE TITLE
Duplicate ABI error thrown for unknown reason

### ISSUE THREAD

**Issue by froggiedev** [ItsNickBarry/hardhat-abi-exporter#45]
https://github.com/ItsNickBarry/hardhat-abi-exporter/blob/4949db3b6db00f91b413ad49254983fb32276b17/tasks/export_abi.js#L71

This line throws when I compile a combination of Uniswap v3 core and periphery contract libraries. I get:

```Error in plugin hardhat-abi-exporter: duplicate output destination: .../uniswap/v3-core/abi/IUniswapV3Factory.json```

when compiling, despite there only being one interface in the whole repo named IUniswapV3Factory.

Disabling this line throws no error.

Perhaps the error is unnecessary since a set is used anyway, so duplicate abi's will just be ignored anyway? or perhaps the abi's should be diffed instead (e.g. using `lodash.isEqual`) and if the diff does not match, then the error thrown.

**Comment by ItsNickBarry** [comment]
Try version `2.10.1`.  If ABIs are equal, the error is ignored.  Reopen if still broken.
