### ISSUE TITLE
Error: ENOTEMPTY: directory not empty, rmdir

### ISSUE THREAD

**Issue by N1ghtly** [ItsNickBarry/hardhat-abi-exporter#5]
When there are files in the output directory the plugin fails, even though I have clear set to true in config.

Full error:
```
{ Error: ENOTEMPTY: directory not empty, rmdir '/Users/solar/dev/eth/tug-of-war/solidity/../dapp/src/abi'
    at Object.rmdirSync (fs.js:684:3)
    at OverriddenTaskDefinition._action (/Users/solar/dev/eth/tug-of-war/solidity/node_modules/hardhat-abi-exporter/index.js:31:8)
  errno: -66,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: '/Users/solar/dev/eth/tug-of-war/solidity/../dapp/src/abi' }
```

**Comment by ItsNickBarry** [comment]
I'm not sure how to reproduce this.  The `recursive` option is set on the `rmdir` call, so a non-empty directory should not be an issue.

**Comment by ItsNickBarry** [comment]
What version of node are you using?  Looks like the `recursive` option was introduced in `12.10.0`.

**Comment by N1ghtly** [comment]
Ahh could very well be I'm on node 10. I'll check it when I get home later tonight!

**Comment by N1ghtly** [comment]
I was on node 10.22. Perhaps you could add node >= 12 as dependency in the readme. Closing!
