### ISSUE TITLE
Support excluding contracts that match a pattern or are in a specific directory?

### ISSUE THREAD

**Issue by chpiatt** [ItsNickBarry/hardhat-abi-exporter#6]
Thanks for this tool, it's super helpful.  One feature I wish it supported is passing in a regex pattern and/or specifying specific subfolders to exclude in the except array.

For example if I had a file structure like:
contracts
L interfaces
..L IERC20.sol
..L IERC721.sol
MyContract.sol
OtherContract.sol

It would be great if I had a way to exclude all of the contracts in the interfaces directory without specifying each of the files individually.  Would you consider adding support for this feature?

**Comment by ItsNickBarry** [comment]
I am considering regex matching.  Just need to decide how that should interact with the existing `only` and `exclude` options.  I will try to get to it by the end of the week.

**Comment by ItsNickBarry** [comment]
@chpiatt Added in `2.1.0`.

**Comment by ItsNickBarry** [comment]
Make that `2.1.1`.
