### ISSUE TITLE
Will this work for vyper?

### ISSUE THREAD

**Issue by Thrasymachus01** [ItsNickBarry/hardhat-abi-exporter#7]
The description explicitly mentions solidity but isn't ABI generation only dependent on the bytecode?
Will it work for vyper too?

**Comment by Thrasymachus01** [comment]
Had a look through the code. Seems it's only checking the artifact files and can therefore support any language. Closing this, but should probably update the description and remove the "Solidity" word as that's a bit confusing.

**Comment by ItsNickBarry** [comment]
Fixed
